import type { Scenario } from '@mockforge/core'

/**
 * Formats scenarios as Dart final Map constants.
 *
 * Output:
 * ```dart
 * // Generated by MockForge — 2024-01-01
 *
 * /// Scenario: Free User
 * final Map<String, dynamic> freeUser = {
 *   'id': 'uuid-...',
 *   ...
 * };
 *
 * final List<Map<String, dynamic>> allScenarios = [freeUser, ...];
 * ```
 */
export function formatAsDart(scenarios: Scenario[]): string {
  const lines: string[] = [
    `// Generated by MockForge — ${new Date().toISOString().slice(0, 10)}`,
    '',
  ]

  const varNames: string[] = []

  for (const scenario of scenarios) {
    const varName = toCamelCase(scenario.name)
    varNames.push(varName)

    const doc = scenario.description
      ? `/// ${scenario.description}`
      : `/// Scenario: ${scenario.name}`

    lines.push(doc)
    lines.push(
      `final Map<String, dynamic> ${varName} = ${dartRepr(scenario.fields)};`
    )
    lines.push('')
  }

  lines.push(
    `final List<Map<String, dynamic>> allScenarios = [${varNames.join(', ')}];`
  )
  lines.push('')

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function toCamelCase(str: string): string {
  const words = str
    .replace(/[^a-zA-Z0-9\s]/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean)

  return words
    .map((w, i) =>
      i === 0
        ? w.toLowerCase()
        : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()
    )
    .join('')
}

/**
 * Converts a JS value to a Dart literal representation.
 */
function dartRepr(value: unknown, indent = 0): string {
  const pad = '  '.repeat(indent)
  const innerPad = '  '.repeat(indent + 1)

  if (value === null) return 'null'
  if (typeof value === 'boolean') return String(value)
  if (typeof value === 'number') return String(value)
  if (typeof value === 'string') return `'${value.replace(/'/g, "\\'")}'`

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]'
    const items = value.map(v => `${innerPad}${dartRepr(v, indent + 1)}`)
    return `[\n${items.join(',\n')},\n${pad}]`
  }

  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value as Record<string, unknown>)
    if (entries.length === 0) return '{}'
    const items = entries.map(
      ([k, v]) => `${innerPad}'${k}': ${dartRepr(v, indent + 1)}`
    )
    return `{\n${items.join(',\n')},\n${pad}}`
  }

  return String(value)
}
