import type { Scenario } from '@mockforge/core'

/**
 * Formats scenarios as MSW v2 (Mock Service Worker) HTTP handlers.
 *
 * The first scenario is used as the default response.
 * Remaining scenarios are included as commented-out alternatives.
 *
 * Output:
 * ```ts
 * import { http, HttpResponse } from 'msw'
 *
 * // TODO: Replace '/api/resource' with your actual endpoint path.
 * export const handlers = [
 *   http.get('/api/resource', () => {
 *     // Default: Free User
 *     return HttpResponse.json({ ... })
 *
 *     // Alternative: Admin User
 *     // return HttpResponse.json({ ... })
 *   }),
 * ]
 * ```
 */
export function formatAsMsw(scenarios: Scenario[], endpoint = '/api/resource'): string {
  if (scenarios.length === 0) return ''

  const [defaultScenario, ...alternatives] = scenarios

  const lines: string[] = [
    `// Generated by MockForge — ${new Date().toISOString().slice(0, 10)}`,
    `import { http, HttpResponse } from 'msw'`,
    '',
    `// TODO: Replace '${endpoint}' with your actual endpoint path.`,
    `export const handlers = [`,
    `  http.get('${endpoint}', () => {`,
    `    // Default scenario: ${defaultScenario!.name}`,
    `    return HttpResponse.json(${JSON.stringify(defaultScenario!.fields, null, 6).replace(/\n/g, '\n    ')})`,
  ]

  if (alternatives.length > 0) {
    lines.push('')
    lines.push(`    // ── Alternative scenarios ────────────────────────────────────────────────`)
    for (const alt of alternatives) {
      lines.push('')
      lines.push(`    // ${alt.name}${alt.description ? ` — ${alt.description}` : ''}`)
      const json = JSON.stringify(alt.fields, null, 6).replace(/\n/g, '\n    ')
      lines.push(`    // return HttpResponse.json(${json})`)
    }
  }

  lines.push(`  }),`)
  lines.push(`]`)
  lines.push(``)

  return lines.join('\n')
}
