import type { Scenario } from '@mockforge/core'

/**
 * Formats scenarios as Python module-level dicts.
 *
 * Output:
 * ```python
 * # Generated by MockForge — 2024-01-01
 * from typing import Any
 *
 * # Scenario: Free User
 * free_user: dict[str, Any] = {
 *   "id": "uuid-...",
 *   ...
 * }
 *
 * ALL_SCENARIOS: list[dict[str, Any]] = [free_user, ...]
 * ```
 */
export function formatAsPython(scenarios: Scenario[]): string {
  const lines: string[] = [
    `# Generated by MockForge — ${new Date().toISOString().slice(0, 10)}`,
    'from typing import Any',
    '',
  ]

  const varNames: string[] = []

  for (const scenario of scenarios) {
    const varName = toSnakeCase(scenario.name)
    varNames.push(varName)

    const comment = scenario.description
      ? `# ${scenario.description}`
      : `# Scenario: ${scenario.name}`

    lines.push(comment)
    lines.push(`${varName}: dict[str, Any] = ${jsonToRepr(scenario.fields)}`)
    lines.push('')
  }

  lines.push('ALL_SCENARIOS: list[dict[str, Any]] = [')
  for (const n of varNames) lines.push(`    ${n},`)
  lines.push(']')
  lines.push('')

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function toSnakeCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9\s]/g, ' ')
    .trim()
    .split(/\s+/)
    .map(w => w.toLowerCase())
    .join('_')
}

/**
 * Converts a JS value to a Python repr string (handles bool, None, str, number, object, array).
 */
function jsonToRepr(value: unknown, indent = 0): string {
  const pad = '    '.repeat(indent)
  const innerPad = '    '.repeat(indent + 1)

  if (value === null) return 'None'
  if (typeof value === 'boolean') return value ? 'True' : 'False'
  if (typeof value === 'number') return String(value)
  if (typeof value === 'string') return JSON.stringify(value)

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]'
    const items = value.map(v => `${innerPad}${jsonToRepr(v, indent + 1)}`)
    return `[\n${items.join(',\n')},\n${pad}]`
  }

  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value as Record<string, unknown>)
    if (entries.length === 0) return '{}'
    const items = entries.map(
      ([k, v]) => `${innerPad}${JSON.stringify(k)}: ${jsonToRepr(v, indent + 1)}`
    )
    return `{\n${items.join(',\n')},\n${pad}}`
  }

  return JSON.stringify(value)
}
